// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/generate-coordinates": {
            "post": {
                "description": "Принимает параметры для генерации маршрута и возвращает только координаты",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Маршруты"
                ],
                "summary": "Генерирует только координаты маршрута",
                "parameters": [
                    {
                        "description": "Параметры запроса",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.RouteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Пример: [[55.7270939,37.6002408], ...]",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array"
                            }
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Ошибка генерации маршрута",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/generate-route": {
            "post": {
                "description": "Принимает параметры для генерации маршрута и возвращает список мест с координатами",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Маршруты"
                ],
                "summary": "Генерирует маршрут с местами и координатами",
                "parameters": [
                    {
                        "description": "Параметры запроса",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.RouteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Place"
                            }
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Ошибка генерации маршрута",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Place": {
            "type": "object",
            "properties": {
                "coordinates": {
                    "description": "Координаты",
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "name": {
                    "description": "Название места",
                    "type": "string"
                }
            }
        },
        "model.RouteRequest": {
            "type": "object",
            "properties": {
                "budget": {
                    "description": "Бюджет",
                    "type": "string"
                },
                "places": {
                    "description": "Список категорий",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "time": {
                    "description": "Время прогулки",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
